name: .NET Core

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    - name: Setup GitHub Packages
      run: dotnet nuget add source https://nuget.pkg.github.com/IanKnighton/index.json -n github -u IanKnighton -p GH_TOKEN --store-password-in-clear-text
    - name: Pack
      run: dotnet pack --configuration Release --no-restore
    - name: Push
      run: dotnet nuget push "bin/Release/Cerealizer.*.nupkg" --source "github"
